# render.yaml
services:
  - type: web
    name: medical-rag-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 5
